services:
    postgres:
        container_name: postgres
        image: postgres:17
        restart: always
        env_file:
          - envs/.env_db
        ports:
          - "5432:5432"
    redis:
        container_name: redis
        image: redis:7.4.1-alpine
        restart: always
        ports:
            - "6379:6379"
    event-pulse:
        build: .
        container_name: event-pulse
        restart: always
        command: >
            sh -c "python manage.py migrate &&
                  uvicorn config.asgi:application --host 0.0.0.0"
        ports:
            - "8050:8000"
        env_file: envs/.env_django_celery
        depends_on:
          - postgres
    celery:
        container_name: celery
        build: .
        restart: always
        command: celery -A config worker --loglevel=info --pool=prefork --concurrency=100 --max-tasks-per-child=100 --max-memory-per-child=200 --without-mingle --without-gossip --without-heartbeat
        depends_on:
          - event-pulse
          - postgres
          - redis
        env_file: envs/.env_django_celery
# NOT IMPLEMENTED YET
#    celery-beat:
#        container_name: celery-beat
#        build: .
#        restart: always
#        command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#        depends_on:
#          - event-pulse
#          - celery
#          - redis
#        env_file: envs/.env_django_celery
