# Generated by Django 5.2.1 on 2025-06-08 19:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.UUIDField(db_index=True)),
                ('level', models.CharField()),
                ('message', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='RelaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('event_code', models.TextField()),
                ('source_host', models.TextField()),
                ('forward_url', models.TextField()),
                ('api_key', models.TextField(blank=True, null=True)),
                ('api_secret', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserHmac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmac_key', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, unique=True)),
                ('processed', models.BooleanField(default=False)),
                ('retry', models.BooleanField(default=False)),
                ('host', models.TextField()),
                ('isvalid_hmac', models.BooleanField(default=False)),
                ('psp_reference', models.TextField()),
                ('event_code', models.TextField()),
                ('payload', models.JSONField()),
                ('relay_settings_fk', models.ManyToManyField(blank=True, to='eventpulse.relaysettings')),
            ],
            options={
                'constraints': [models.UniqueConstraint(models.F('psp_reference'), models.F('event_code'), name='psp_reference_event_code_idx')],
            },
        ),
    ]
