# Generated by Django 5.2.1 on 2025-06-10 08:58

import apps.eventpulse.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaysettings',
            name='api_key',
            field=apps.eventpulse.fields.EncryptedField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relaysettings',
            name='api_secret',
            field=apps.eventpulse.fields.EncryptedField(blank=True, null=True),
        ),
    ]
