# Generated by Django 5.2.1 on 2025-06-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpulse', '0002_alter_relaysettings_api_key_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHmac',
        ),
    ]
