# Generated by Django 5.2.1 on 2025-06-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventpulse', '0003_delete_userhmac'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='event_id',
            new_name='uuid',
        ),
    ]
